site_name: neuromorpho-data
repo_url: https://github.com/kpeez/neuromorpho-data
site_url: https://kpeez.github.io/neuromorpho-data
site_description: Lightweight python package for downloading neuron morphologies from the NeuroMorpho archive.
site_author: Kyle Puhger

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
copyright: Maintained by Kyle Puhger.
theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: white
    accent: blue
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
