[tool.poetry]
name = "neuromorpho_data"
version = "0.0.1"
description = "Lightweight python package for downloading neuron morphologies from the NeuroMorpho archives."
authors = ["Kyle Puhger <fkrpuhger@gmail.com>"]
repository = "https://github.com/kpeez/neuromorpho-data"
documentation = "https://kpeez.github.io/neuromorpho-data/"
readme = "README.md"
packages = [
  {include = "neuromorpho_data"}
]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pandas = "^1.5.0"
numpy = "^1.23.3"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.17.1"
black = "^22.10"
isort = "^5.10.1"
flake8 = "^6.0"
flake8-bugbear = "^22.9.11"
flake8-comprehensions = "^3.10.1"
flake8-simplify = "^0.19.3"
flake8-annotations = "^2.9.1"
flake8-docstrings = "^1.6.0"
flake8-unused-arguments = "^0.0.11"
mypy = "^0.991"
pre-commit = "^2.20.0"
types-requests = "^2.28.11.5"
pandas-stubs = "^1.5.2.221213"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.2"
mkdocs-material = "^8.5.10"
mkdocstrings = {extras = ["python"], version = "^0.19.0"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
include = '\.pyi?$'
target-version = ['py310']
fast = true
exclude = '''
(
  /(                        # exclude a few common directories in the
    \.git                   # root of the project
    | \.pytest_cache
    | python-venv
    | \.venv
    | build
    | dist
  ))
'''

[tool.isort]
profile = "black"
skip = ["neuromorpho-data",".venv"]

[tool.mypy]
files = ["neuromorpho_data"]
plugins = "numpy.typing.mypy_plugin"
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true
exclude = [
    '\.venv',
    'tests'
]

[[tool.mypy.overrides]]
module = [
"neuromorpho_api"
]
ignore_missing_imports = true